version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/app/common/'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'npm'
    directory: '/app/auth/'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'docker'
    directory: '/app/auth/'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'npm'
    directory: '/app/client/'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'docker'
    directory: '/app/client/'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'npm'
    directory: '/app/tickets/'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'docker'
    directory: '/app/tickets/'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'npm'
    directory: '/app/nats-test/'
    schedule:
      interval: 'daily'
  # - package-ecosystem: 'docker'
  #   directory: '/app/nats-test/'
  #   schedule:
  #     interval: 'daily'
