apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-svc
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: ticketing.dev
      http:
        paths:
          # - path: /api/payments/?(.*)
          #   backend:
          #     serviceName: payments-svc
          #     servicePort: 3000
          - path: /api/users/?(.*)
            pathType: 'Prefix'
            backend:
              service:
                name: auth-svc
                port:
                  number: 3000
          - path: /api/tickets/?(.*)
            pathType: 'Prefix'
            backend:
              service:
                name: tickets-svc
                port:
                  number: 3000
          # - path: /api/orders/?(.*)
          #   backend:
          #     serviceName: orders-svc
          #     servicePort: 3000
          - path: /?(.*)
            pathType: 'Prefix'
            backend:
              service:
                name: client-svc
                port:
                  number: 3000
